/obj/machinery/vending/wardrobe/sec_wardrobe
	product_categories = list(
		list(
			"name" = "Main",
			"icon" = "shield",
			"products" = list(
		/obj/item/clothing/glasses/hud/security/sunglasses = 3,
		/obj/item/clothing/head/beret/sec = 3,
//		/obj/item/clothing/head/beret/sec/black = 3,
		/obj/item/clothing/head/costume/ushanka/sec = 3,
		/obj/item/clothing/head/soft/sec = 3,
		/obj/item/clothing/mask/bandana/striped/security = 3,
		/obj/item/clothing/under/rank/security/officer = 3,
//		/obj/item/clothing/under/rank/security/officer/black = 3,
		/obj/item/clothing/under/rank/security/officer/skirt = 3,
//		/obj/item/clothing/under/rank/security/officer/dress = 3,
//		/obj/item/clothing/under/rank/security/officer/skirt/mini = 3,
//		/obj/item/clothing/under/rank/security/officer/turtleneck = 3,
//		/obj/item/clothing/under/rank/security/officer/fancy = 3,
//		/obj/item/clothing/under/rank/security/officer/utility = 3,
//		/obj/item/clothing/under/rank/security/officer/trousers = 3,
//		/obj/item/clothing/under/rank/security/officer/trousers/shorts = 3,
		/obj/item/clothing/suit/armor/vest/secjacket = 3,
		/obj/item/clothing/suit/hooded/wintercoat/security = 3,
		/obj/item/clothing/suit/armor/vest = 3,
		/obj/item/clothing/gloves/color/black/security = 3,
		/obj/item/clothing/shoes/jackboots/sec = 3,
		/obj/item/storage/backpack/security = 3,
		/obj/item/storage/backpack/satchel/sec = 3,
		/obj/item/storage/backpack/duffelbag/sec = 3,
		/obj/item/storage/backpack/messenger/sec = 3,
//		/obj/item/clothing/neck/security_cape = 3,
//		/obj/item/clothing/neck/security_cape/armplate = 3,
		),
	),

		list(
			"name" = "Alternate",
			"icon" = "shield-halved",
			"products" = list(
//		/obj/item/clothing/glasses/hud/security/sunglasses/blue = 3,
//		/obj/item/clothing/head/beret/sec/blue = 3,
//		/obj/item/clothing/head/beret/sec/black/alt = 3,
//		/obj/item/clothing/head/costume/ushanka/sec/blue = 3,
//		/obj/item/clothing/head/soft/sec/alt = 3,
//	/obj/item/clothing/under/rank/security/blue/officer = 3,
//		/obj/item/clothing/under/rank/security/blue/skirt = 3,
//bluesh/obj/item/clothing/under/rank/security/blue/shirt = 3,
//		/obj/item/clothing/under/rank/security/blue/dress = 3,
//		/obj/item/clothing/under/rank/security/blue/skirt/plain = 3,
//		/obj/item/clothing/under/rank/security/blue/skirt/mini/blue = 3,
//		/obj/item/clothing/under/rank/security/blue/turtleneck/blue = 3,
//		/obj/item/clothing/under/rank/security/blue/formal/blue = 3,
//		/obj/item/clothing/under/rank/security/blue/utility/blue = 3,
//		/obj/item/clothing/under/rank/security/blue/trousers/blue = 3,
//		/obj/item/clothing/under/rank/security/blue/trousers/shorts/blue = 3,
//respri/obj/item/clothing/suit/hooded/wintercoat/security/blue = 3,
//		/obj/item/clothing/suit/armor/vest/secjacket/blue = 3,
//		/obj/item/clothing/suit/armor/vest/alt = 3,
//		/obj/item/clothing/gloves/color/black/security/white = 3,
//		/obj/item/clothing/gloves/color/black/security/blu = 3,
//		/obj/item/clothing/shoes/jackboots/sec/blue = 3,
//warden/obj/item/clothing/head/hats/warden/police/patrol = 3,
//		/obj/item/storage/backpack/security/blue = 3,
//		/obj/item/storage/backpack/satchel/sec/blue = 3,
//		/obj/item/storage/backpack/duffelbag/sec/blue = 3,
//		/obj/item/storage/backpack/messenger/sec/blue = 3,
			),
		),

	premium = list(
		/obj/item/clothing/under/rank/security/officer/formal = 3,
		/obj/item/clothing/suit/jacket/officer/blue = 3,
		/obj/item/clothing/head/beret/sec/navyofficer = 3,
		/obj/item/clothing/mask/placeholder/green/camo = 3,
		/obj/item/clothing/mask/placeholder/green = 3,
		/obj/item/clothing/mask/placeholder/tan = 3,
		/obj/item/clothing/under/pants/camo = 3,
	)
)
